Ht18
kirkenj/testRepo pull request #15
Opened 2022-09-25 19:13 UTC by kirkenj

2022-09-25 19:19 UTC, kirkenj commented on HT18/Controllers/HomeController.cs
> +        };
создан статическое поле паркинга и реализованы основные методы управления последним

2022-09-25 19:19 UTC, kirkenj commented on HT18/Controllers/HomeController.cs
> +        }
Сюда переадресуются все вызовы основных методов. Тут выводится таблица с машинками

2022-09-25 19:19 UTC, kirkenj commented on HT18/Controllers/HomeController.cs
> +        }
Добавление машины. Также реализован вывод исключения (Пока такой, на который хватило смышленности)

2022-09-25 19:19 UTC, kirkenj commented on HT18/Controllers/HomeController.cs
> +        }
Удаление

2022-09-25 19:19 UTC, kirkenj commented on HT18/Controllers/HomeController.cs
> +        }
Заправка

2022-09-25 19:19 UTC, kirkenj commented on HT18/Controllers/HomeController.cs
> +        }
"Выгул" машины

2022-09-25 19:19 UTC, kirkenj commented on HT18/Views/Home/Index.cshtml
> +}
уведомление об ошибке

2022-09-25 19:19 UTC, kirkenj commented on HT18/Views/Home/Index.cshtml
> +</table>
Табличка с машинами

2022-09-25 19:21 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192161471-aee50d46-a9be-4f5b-80bc-130c5de7efc0.png)
Главная страница

2022-09-25 19:22 UTC, kirkenj commented
https://localhost:7222/Home/AddCar?identifier=meow&fuel=2&enginePower=3000&tankCapacity=2000
![image](https://user-images.githubusercontent.com/57506313/192161490-dd13e48e-4796-40bb-b97a-9e92cc346ca9.png)

2022-09-25 19:23 UTC, kirkenj commented
https://localhost:7222/Home/AddCar?identifier=meow&fuel=Disel&enginePower=3000&tankCapacity=-2000
Сообщение об исключении
![image](https://user-images.githubusercontent.com/57506313/192161508-c7f7f2b8-5c31-4d29-be42-4593afd2520a.png)

2022-09-25 19:23 UTC, kirkenj commented
https://localhost:7222/Home/FillCarTank?index=0&volume=200
![image](https://user-images.githubusercontent.com/57506313/192161537-01763df3-df79-4a61-ac70-a42bbdbb1c13.png)

2022-09-25 19:24 UTC, kirkenj commented
https://localhost:7222/Home/SendCarForARide?index=0
![image](https://user-images.githubusercontent.com/57506313/192161546-13685032-db39-4673-865c-da97d3a8b173.png)

2022-09-25 19:24 UTC, kirkenj commented
https://localhost:7222/Home/RemoveCar?index=3
![image](https://user-images.githubusercontent.com/57506313/192161570-a1bad9df-c4d6-4230-b4fd-471856f3a7af.png)

2022-09-25 19:32 UTC, kirkenj commented
@alexeybruy

2022-09-26 15:21 UTC, kirkenj commented
Т.к. вы проверили домашки за 40 минут до отправки 18й домашки, то я сюда и 19 приделал

2022-09-26 15:23 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192316340-891d8bbb-3952-48b7-916f-697b34e4394b.png)
главная страница. Мастер-страница содержит только Add car и Home. Больше не добавил, т.к. остальной функционал реализует главная страница

2022-09-26 15:24 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192316692-79cbb041-0270-4ed4-b4c6-4dc06553f47d.png)
![image](https://user-images.githubusercontent.com/57506313/192316714-f24f5a4f-8060-4d83-8b63-0f9429521414.png)
Добаление машинки

2022-09-26 15:28 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192317639-30921056-509a-4ba2-a72e-f4a391d11499.png)
![image](https://user-images.githubusercontent.com/57506313/192317677-33ccb76d-1370-4a5f-a2e4-ad09120cc92c.png)
Добавление машины

2022-09-26 15:29 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192317796-d3eeb2fa-4c8c-4685-87d8-2f095b81f9d0.png)
нажал кнопку, отправляющую машину "покататься" для 3го индекса

2022-09-26 15:30 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192317929-a108784c-525c-49b4-ae4a-7080243895e1.png)
редакция 3го индекса и применение ей нового топлива - Disel

2022-09-26 15:30 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192318073-513e33e2-5b8c-48dd-b4af-77d165b01ac0.png)

2022-09-26 15:30 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192318157-77a0df84-b2b0-435d-bcc7-0a23ff9eedc0.png)
![image](https://user-images.githubusercontent.com/57506313/192318173-4f5f7a21-9f0e-42cf-a8b2-775e41db15b1.png)
"заправка" авто

2022-09-28 11:22 UTC, kirkenj commented
Создавать пользовательские исключения не стал, просто добавил Middlewares. Код уже был ориентирован бросать исключения, так что все получилось очень быстро. Формулировка с луковицей подходит лучше всего для них, по-моему, ведь мы оборачиваем вызов следующего делегата запроса в пользовательский код. Пришлось уделить внимание на иерархию ошибок в языке, чтобы Middleware работали как задумано, но это буквально всего лишь менять строки порядком. Далее ошибки выглядят так:

2022-09-28 11:24 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192766715-89130be6-bae5-4ef0-ac5a-8bd08e3541a4.png)
![image](https://user-images.githubusercontent.com/57506313/192766750-4e42d591-2e85-4910-8392-569afd6bc9e4.png)
![image](https://user-images.githubusercontent.com/57506313/192766780-38f519dd-02e0-4b78-a19c-075644c201fe.png)
Немного смущает, что Visual studio обязательно показывает исключение, но все работает
Тут была попытка создать машину, не указав ничего, кроме топлива

2022-09-28 11:25 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192767019-680fd07d-a79b-4afc-a162-b18e985b39de.png)
![image](https://user-images.githubusercontent.com/57506313/192767051-23099b6d-805c-402a-aaeb-006ffee81657.png)
![image](https://user-images.githubusercontent.com/57506313/192767069-e3180302-348d-40db-ab85-b0e9b1cf87c6.png)
Попытка заправить авто -1 единицей топлива

2022-09-28 11:26 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/192767193-873e81b9-4da5-4dd8-b086-44bcbeb7776a.png)
![image](https://user-images.githubusercontent.com/57506313/192767215-a67f06a1-30df-4249-9f16-797bd72cc983.png)
попытка отправить машину "покататься" без топлива

2022-10-05 09:48 UTC, alexeybruy requested changes
18,19 - ок, 20 - доделать

2022-10-05 09:48 UTC, alexeybruy commented on HT18/Middlewares/ArgumentOutOfRangeExceptionMiddleware.cs
> +            catch (ArgumentOutOfRangeException ex)
концепция правильная, но предполагалось создание собственных исключений. Необходимо понять какая ошибка может часто встречаться, создать для нее исключение, и выполнять `throw` этого исключения в том случае. А после таким же образом отлавливать тут

2022-10-06 15:05 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/194348707-e5961af4-d6ed-4264-b298-c2588fda90c7.png)
![image](https://user-images.githubusercontent.com/57506313/194348740-a75a5a8c-4229-4689-ad60-d01538b04a10.png)
ArgumentException

2022-10-06 15:07 UTC, kirkenj commented
![image](https://user-images.githubusercontent.com/57506313/194349147-db7b910e-7732-4b63-9cd3-1c530444c724.png)
![image](https://user-images.githubusercontent.com/57506313/194349187-54229557-f631-409d-bfbd-6994128eba19.png)
![image](https://user-images.githubusercontent.com/57506313/194349230-f494f615-3ffb-4e86-9857-9bd95947cded.png)
outOfRangeException

2022-10-06 15:07 UTC, kirkenj commented
понял, что при несколько неправильных условиях их бросал, но воть

2022-10-19 09:15 UTC, alexeybruy approved these changes
выглядит супер

2022-10-19 19:05 UTC, merged