Ht9
kirkenj/testRepo pull request #7
Opened 2022-07-06 11:53 UTC by kirkenj

Created a "ClassLibraryForHT9" for "ProductInventoryProjectUsingClasses"

2022-07-15 14:14 UTC, alexeybruy requested changes

2022-07-15 14:14 UTC, alexeybruy commented on ClassLibraryForHT9/Models/Product.cs
> +        public double Price
сделайте internal

2022-07-18 12:48 UTC, kirkenj commented on ClassLibraryForHT9/Models/Product.cs
> +        public double Price
готово

2022-07-22 20:49 UTC, alexeybruy approved these changes

2022-07-22 22:24 UTC, closed without merging